# Generated by Django 5.2.8 on 2025-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedvideo",
            name="error_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="generatedvideo",
            name="generation_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generatedvideo",
            name="generation_progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
