# Generated by Django 5.2.8 on 2025-11-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_generatedvideo_error_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedvideo",
            name="generation_progress",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
