# Generated by Django 5.2.8 on 2025-11-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_ensure_generation_progress_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedvideo",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Optional. Leave blank to generate the video from the audio track.",
                null=True,
                upload_to="videos/",
            ),
        ),
    ]
