# Generated by Django 5.2.8 on 2025-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_alter_generatedvideo_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedvideo",
            name="generation_progress",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
