# Generated by Django 5.2.8 on 2025-11-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_aiproviderconfig_aivideojob"),
        ("videos", "0007_backgroundvideo_generatedvideo_background_video"),
    ]

    operations = []
