# Generated by Django 5.2.8 on 2025-11-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_backgroundvideo_generatedvideo_background_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedvideo",
            name="extra_prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generatedvideo",
            name="style",
            field=models.CharField(
                choices=[
                    ("lyric_simple", "Simple Lyric Video"),
                    ("karaoke", "Karaoke Style"),
                    ("motion_graphic", "Abstract Motion Graphics"),
                    ("dark_emotional", "Dark Emotional"),
                    ("romantic", "Romantic"),
                    ("rap_hiphop", "Rap / Hip-Hop"),
                    ("cyberpunk", "Cyberpunk / Neon City"),
                    ("ai_surreal", "AI Surreal / Abstract"),
                    ("cinematic", "Epic Cinematic"),
                    ("landscape", "Nature Landscape"),
                    ("party_edm", "EDM / Party"),
                    ("ai_avatar", "AI Avatar Performance"),
                ],
                default="lyric_simple",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="generatedvideo",
            name="style_prompt",
            field=models.TextField(blank=True),
        ),
    ]
